boards:
  # - model: "nrf52840dk_nrf52840"  # Board model
  #   snr: "1050289157"  # Serial number
  #   ppk: "E373C904"  # PPK (Power Profiling Kit) serial number
  - model: nrf52840dk_nrf52840  # Board model
    snr: 1050242564  # Serial number
    ppk: FEA55411  # PPK (Power Profiling Kit) serial number
  # - model: nrf52840dk_nrf52840  # Board model
  #   snr: 1050283223  # Serial number
  #   ppk: FAFD344C  # PPK (Power Profiling Kit) serial number
  # - model: nrf52833dk_nrf52833  # Board model
  #   snr: 685756103  # Serial number
  #   ppk: None  # PPK (Power Profiling Kit) serial number (unit: N/A)
  # - model: nrf5340dk_nrf5340_cpuapp  # Board model
  #   snr: 1050006605  # Serial number
  #   ppk: None  # PPK (Power Profiling Kit) serial number (unit: N/A)


# DATASETS and EXPERIMENT
datasets:
  - "speech_commands"  # Dataset name
  - "motion_sense_accelerometer"  # Dataset name
  - "corscience"
  - "daliac"

experiment_description: daliac # Experiment description

# DATASET
dataset: "daliac"  # Dataset name
sample_rate: 500  # Sample rate (units: Hz)
input_shape: [5000, 1]  # Input shape (units: [samples, channels])
nb_classes: 1  # Number of classes
classes_filter: [] #[0, 2, 6, 8]  # List of classes used for optimization

# EvoNAS hyper-parameters
nb_generations: 20  # Number of generations
population_size: 100  # Population size
nb_best_models_crossover: 25  # Number of models used for crossover
mutation_rate: 20  # Mutation rate (units: percent)
max_nb_feature_layers: 20  # Max number of layers before GAP, GMP, or Flatten
max_nb_classification_layers: 6  # Max number of layers after GAP, GMP, or Flatten
path_gene_pool: gene_pool.txt  # File path for gene pool
path_rule_set: rule_set.txt  # File path for rule set
power_measurement_nb_samples_average: 100  # Number of samples for power measurement averaging
power_measurement_threshold: 4000  # Power measurement threshold (units: uA)

# DNN training hyper-parameters
nb_epochs: 10  # Number of epochs
min_free_space_gpu: 6000000000  # Minimum free space on GPU (units: bytes)

# Constraints
max_memory_footprint: 800000  # Maximum memory footprint (units: Bytes)
max_inference_time: 200  # Maximum inference time (units: ms)
max_energy_consumption: 2  # Maximum energy consumption (units: mJ)
