import os.path
import signal
from subprocess import Popen

from coolname import generate_slug
import json
import numpy as np
import time
import subprocess
import nvidia_smi
from multiprocessing import Pool

from .src.genepool import GenePool
from .src.translation import translate
from utils.saver import Saver
from utils.loader import Loader
from .src.fitness import calculate_fitness

from multiprocessing import get_context


class GeneticAlgorithm:
    def __init__(self, params: dict, saver: Saver, loader: Loader=None):
        self.params = params
        self.my_saver = saver
        self.my_gene_pool = GenePool(params)

        # define all variables that change after each generation
        if loader is None:
            self.population_genotype = None  # dicts containing all individuals with its properties
        else:
            # load all genotypes --> each of them will get a new name but that's the easiest solution I found for now
            self.population_genotype = loader.load_population_genotype()

        self.individuals_names = None  # randomly created names for all individuals within one generation
        self.preselected_individuals = None  # preselected individuals (names) after accuracy/memory footprint determination
        self.parents_names = None  # list containing the chromosome names of the parents that yielded to a new chromosome
        self.population_phenotype = None  # generated TF models
        self.population_phenotype_tflite = None  # generated TFLite models
        self.generation_counter = None  # information in which generation we are currently
        self.population_next_generation = None  # contains all individuals for next generation (determined through selection, crossover and mutation)
        self.best_models_current_generation = None  # contains the best models of the current generation

    def init_first_generation(self):
        self.population_genotype = []
        for _ in range(self.params['population_size']):
            random_chromosome = self.my_gene_pool.get_random_chromosome()
            self.population_genotype.append(random_chromosome)

    def train_neural_networks(self):
        # train all neural networks
        # --> start several training processes here
        print("trainning")
        idx = 0
        print(len(self.individuals_names))
        while idx < len(self.individuals_names):
            command = 'python genetic_algorithm/src/train.py ' + \
                        f'--results_dir {self.my_saver.results_dir} ' + \
                        f'--gen_dir Generation_{self.generation_counter} ' + \
                        f'--individual_dir {self.individuals_names[idx]} ' + \
                        f'--nb_epochs {self.params["nb_epochs"]} ' + \
                        f'--dataset {self.params["dataset"]} ' + \
                        f'--classes_filter ' + ' '.join(str(i) for i in self.params["classes_filter"])
            idx += 1
            subprocess.call(command,stdout=subprocess.PIPE, shell=True)
            print("doje")
            time.sleep(15)


    def selection(self):
        # calculate fitness of all preselected models
        path = f'{self.my_saver.results_dir}/Generation_{self.generation_counter}/'
        models_with_fitness = dict()
        for individual in self.individuals_names:
            with open(path + individual + '/results.json', 'r') as f:
                results = json.loads(f.read())
                fitness = calculate_fitness(results, self.params)

                # save fitness together with the individual name to sort and select them later
                models_with_fitness[f'{individual}'] = fitness

            # save fitness in results.json
            with open(path + individual + '/results.json', 'w') as f:
                results['fitness'] = float(fitness)
                json.dump(results, f, indent=2)

        # sort them by their achieved fitness
        models_with_fitness = sorted(models_with_fitness.items(), key=lambda item: item[1], reverse=True)

        # save the model with the best fitness to find it easier later on
        self.my_saver.save_best_individual(self.generation_counter, models_with_fitness[0])

        self.best_models_current_generation = \
            [models_with_fitness[i][0] for i in range(self.params['nb_best_models_crossover']) if
             i < len(models_with_fitness)]

    def crossover(self):
        """ Crossover the best chromosomes to get the population for the next generation. """
        self.population_next_generation, self.parents_names = self.my_gene_pool.crossover(
            path=f'{self.my_saver.results_dir}/Generation_{self.generation_counter}/',
            fittest_chromosomes=self.best_models_current_generation)

    def mutation(self):
        """ Mutation of the population previously generated by crossover. """
        self.population_genotype = []
        for chromosome in self.population_next_generation:
            mutated_chromosome = self.my_gene_pool.mutate_chromosome(chromosome)
            self.population_genotype.append(mutated_chromosome)

    def _process_model_translation(self, chromosome):
        try:
            model = translate(chromosome, self.params['input_shape'], self.params['nb_classes'])
        except:
            raise ValueError(f"Error when translating from genotype to phenotype. Chromosome: {chromosome}")    
        return model  

    def prepare_generation(self, current_generation: int):
        self.individuals_names = []
        self.population_phenotype = []
        self.population_phenotype_tflite = []
        self.preselected_individuals = []
        self.best_models_current_generation = []
        self.population_next_generation = []

        self._generate_individuals_names()
        if self.parents_names is not None:
            self.my_saver.save_parents(self.generation_counter, self.individuals_names, self.parents_names)
            self.parents_names = None

        self.generation_counter = current_generation

        # convert chromosomes to models and to tflite models in parallel
        with get_context("spawn").Pool(os.cpu_count()) as pool:

            models = pool.map(self._process_model_translation, self.population_genotype)
            # translate all chromosomes: genotype (chromosome) --> phenotype (tf.keras.Model)

        # save models 
        for model in models:
            self.population_phenotype.append(model)


        # save untrained networks such that it can be loaded in a new process
        self.my_saver.save_chromosomes(self.population_genotype, self.population_phenotype, self.individuals_names,
                                       self.generation_counter)

    def _generate_individuals_names(self):
        self.individuals_names = []
        for _ in range(self.params['population_size']):
            # Assigning a random name to an individual to make it easier to track results
            random_name = generate_slug(2).replace("-", "_")
            while random_name in self.individuals_names:  # --> make sure that the random name does not already exist
                random_name = generate_slug(2).replace("-", "_")
            self.individuals_names.append(random_name)
